{% set name = "ponio" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/hpc-maths/ponio/archive/v{{ version }}.tar.gz
  sha256: 771b14b501ceb2c7a0dea50bacbf5e1b0d13223b280bda19a6f9845e41c3be34

build:
  number: 1

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake
    - make  # [unix]
    - ninja  # [win]
    - sympy
    - numpy
    - jinja2

test:
  commands:
    - test -d ${PREFIX}/include/ponio  # [unix]
    - test -f ${PREFIX}/include/ponio/solver.hpp  # [unix]
    - test -f ${PREFIX}/share/ponio/ponioConfig.cmake  # [unix]
    - test -f ${PREFIX}/share/ponio/ponioConfigVersion.cmake  # [unix]
    - if not exist %LIBRARY_PREFIX%\include\ponio\solver.hpp (exit 1)  # [win]
    - if not exist %LIBRARY_PREFIX%\share\ponio\ponioConfig.cmake (exit 1)  # [win]
    - if not exist %LIBRARY_PREFIX%\share\ponio\ponioConfigVersion.cmake (exit 1)  # [win]

about:
  home: https://github.com/hpc-maths/ponio
  summary: Presentation Overview of Numerical Integrator for ODE
  description: |
    The library ponio is a collection of time integrators for solving ODE and PDE written in C++. This library aims to be the easiest to use without compromising on performance.
  license: BSD-3-Clause
  license_file: LICENSE
  doc_url: https://ponio.readthedocs.io/

extra:
  recipe-maintainers:
    - kivvix
