{% set name = "ponio" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/hpc-maths/ponio/archive/v{{ version }}.tar.gz
  sha256: 758929cf49509896063a1a3e989423debb60ce149e892c4c9130f8f7f6dc5ac4

build:
  noarch: generic
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make  # [unix]
    - ninja  # [win]
    - sympy
    - numpy
    - jinja2
  run:
    - __unix  # [unix]
    - __win  # [win]

test:
  commands:
    - test -d ${PREFIX}/include/ponio  # [unix]
    - test -f ${PREFIX}/include/ponio/solver.hpp  # [unix]
    - test -f ${PREFIX}/share/ponio/ponioConfig.cmake  # [unix]
    - test -f ${PREFIX}/share/ponio/ponioConfigVersion.cmake  # [unix]
    - if not exist %LIBRARY_PREFIX%\include\ponio\solver.hpp (exit 1)  # [win]
    - if not exist %LIBRARY_PREFIX%\share\ponio\ponioConfig.cmake (exit 1)  # [win]
    - if not exist %LIBRARY_PREFIX%\share\ponio\ponioConfigVersion.cmake (exit 1)  # [win]

about:
  home: https://github.com/hpc-maths/ponio
  summary: Presentation Overview of Numerical Integrator for ODE
  description: |
    The library ponio is a collection of time integrators for solving ODE and PDE written in C++. This library aims to be the easiest to use without compromising on performance.
  license: BSD-3-Clause
  license_file: LICENSE
  doc_url: https://ponio.readthedocs.io/

extra:
  recipe-maintainers:
    - kivvix
